{
    "project": "openbmc/bmcweb",
    "branch": "master",
    "id": "I5e2025ec8b264a38cbf5bb944142c83c0486ce50",
    "number": 45822,
    "subject": "Fix update_schemas script",
    "owner": {
        "name": "Szymon Dompke",
        "email": "szymon.dompke@intel.com",
        "username": "sdompke"
    },
    "url": "https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/45822",
    "commitMessage": "Fix update_schemas script\n\nScript update_schemas.py was incorrectly generating schemas since change\nf395daac96c8122623700c2b124d905266ea8223. This was caused by treating\n'edm' as 'edmx' during parse process.\n\nAdditionally, glob pattern was incorrectly skipping all files starting\nwith letter 'O', instead of 'Oem' phrase. This lead to python exceptions\nduring generation, as the script was trying to recreate existing\ndirectories like 'OperatingConfig'.\n\nUnused imports were removed.\n\nTested:\n- running update_schemas.py no longer generates malformed data and no\n  exception were thrown.\n- all files generated by update_schemas.py are generated identically as\n  before regression.\n\nSigned-off-by: Szymon Dompke <szymon.dompke@intel.com>\nChange-Id: I5e2025ec8b264a38cbf5bb944142c83c0486ce50\n",
    "createdOn": 1628706131,
    "lastUpdated": 1629148423,
    "open": false,
    "status": "MERGED",
    "comments": [
        {
            "timestamp": 1628706131,
            "reviewer": {
                "name": "Szymon Dompke",
                "email": "szymon.dompke@intel.com",
                "username": "sdompke"
            },
            "message": "Uploaded patch set 1."
        },
        {
            "timestamp": 1628706165,
            "reviewer": {
                "name": "OpenBMC CI",
                "email": "openbmcbump-ci@yahoo.com",
                "username": "jenkins-openbmc-ci"
            },
            "message": "Patch Set 1: Ok-To-Test+1\n\nUser approved, CI ok to start"
        },
        {
            "timestamp": 1628706576,
            "reviewer": {
                "name": "OpenBMC CI",
                "email": "openbmcbump-ci@yahoo.com",
                "username": "jenkins-openbmc-ci"
            },
            "message": "Patch Set 1: Verified+1\n\nBuild Successful \n\nhttps://jenkins.openbmc.org/job/ci-repository/24230/ : SUCCESS"
        },
        {
            "timestamp": 1628707567,
            "reviewer": {
                "name": "Gunnar Mills",
                "email": "gmills@us.ibm.com",
                "username": "gtmills"
            },
            "message": "Patch Set 1: Code-Review+1\n\nThanks for the commit! Seems good to me. Would like Ed to look. \n\nThis just got missed in testing https://github.com/openbmc/bmcweb/commit/f395daac96c8122623700c2b124d905266ea8223  ?"
        },
        {
            "timestamp": 1628754496,
            "reviewer": {
                "name": "Krzysztof Grobelny",
                "email": "krzysztof.grobelny@intel.com",
                "username": "krzysztof-i"
            },
            "message": "Patch Set 1: Code-Review+1"
        },
        {
            "timestamp": 1628792630,
            "reviewer": {
                "name": "Ed Tanous",
                "email": "ed@tanous.net",
                "username": "edtanous"
            },
            "message": "Patch Set 1:\n\n(1 comment)"
        },
        {
            "timestamp": 1628794221,
            "reviewer": {
                "name": "Gunnar Mills",
                "email": "gmills@us.ibm.com",
                "username": "gtmills"
            },
            "message": "Patch Set 1:\n\n(1 comment)"
        },
        {
            "timestamp": 1628800813,
            "reviewer": {
                "name": "Ed Tanous",
                "email": "ed@tanous.net",
                "username": "edtanous"
            },
            "message": "Patch Set 1:\n\n(1 comment)"
        },
        {
            "timestamp": 1628808999,
            "reviewer": {
                "name": "Szymon Dompke",
                "email": "szymon.dompke@intel.com",
                "username": "sdompke"
            },
            "message": "Patch Set 1:\n\nI did not say that schemas inside bmcweb repo were malformed, but that the current version of update_schemas.py is generating malformed ones. As to why didn't they change - thankfully, this script was not run after it was broken, so all schemas are currently fine. That is why my change is just a modification to the script. You can also see for yourself and run it from current master branch."
        },
        {
            "timestamp": 1629148401,
            "reviewer": {
                "name": "Ed Tanous",
                "email": "ed@tanous.net",
                "username": "edtanous"
            },
            "message": "Patch Set 1:\n\n> Patch Set 1:\n> \n> I did not say that schemas inside bmcweb repo were malformed, but that the current version of update_schemas.py is generating malformed ones. As to why didn't they change - thankfully, this script was not run after it was broken, so all schemas are currently fine. That is why my change is just a modification to the script. You can also see for yourself and run it from current master branch.\n\nGot it."
        },
        {
            "timestamp": 1629148421,
            "reviewer": {
                "name": "Ed Tanous",
                "email": "ed@tanous.net",
                "username": "edtanous"
            },
            "message": "Patch Set 1: Code-Review+2"
        },
        {
            "timestamp": 1629148423,
            "reviewer": {
                "name": "Ed Tanous",
                "email": "ed@tanous.net",
                "username": "edtanous"
            },
            "message": "Change has been successfully rebased and submitted as d699cf969aea5a059b95151f58e054c928f076cc by Ed Tanous"
        }
    ],
    "patchSets": [
        {
            "number": 1,
            "revision": "669bf53dffeb244bcc5564c449eeb5c43f1b8f7f",
            "parents": [
                "735ef6d87392d643901ffede8042652b29d8cce7"
            ],
            "ref": "refs/changes/22/45822/1",
            "uploader": {
                "name": "Szymon Dompke",
                "email": "szymon.dompke@intel.com",
                "username": "sdompke"
            },
            "createdOn": 1628706131,
            "author": {
                "name": "Szymon Dompke",
                "email": "szymon.dompke@intel.com",
                "username": "sdompke"
            },
            "kind": "REWORK",
            "comments": [
                {
                    "file": "scripts/update_schemas.py",
                    "line": 0,
                    "reviewer": {
                        "name": "Ed Tanous",
                        "email": "ed@tanous.net",
                        "username": "edtanous"
                    },
                    "message": "You've changed this script, but I don't see any changes to the related schema files.  Did you re-run it after your changes and check in the new files?"
                },
                {
                    "file": "scripts/update_schemas.py",
                    "line": 0,
                    "reviewer": {
                        "name": "Gunnar Mills",
                        "email": "gmills@us.ibm.com",
                        "username": "gtmills"
                    },
                    "message": "I cherry-picked this and tested. No schemas changed. And that is what that 2nd part of the testing statement is saying. \n\nTested:\n- running update_schemas.py no longer generates malformed data and no\n  exception were thrown.\n- all files generated by update_schemas.py are generated identically as\n  before regression."
                },
                {
                    "file": "scripts/update_schemas.py",
                    "line": 0,
                    "reviewer": {
                        "name": "Ed Tanous",
                        "email": "ed@tanous.net",
                        "username": "edtanous"
                    },
                    "message": "I'm super confused then.  The commit message says \"running update_schemas.py no longer generates malformed data\" and the line on 186 looks like an actual functional change in the schemas we're generating.  If the schemas were malformed and now they're not, why didn't they change?  I feel like I'm missing something here, but I'm not sure what."
                }
            ],
            "files": [
                {
                    "file": "/COMMIT_MSG",
                    "type": "ADDED",
                    "insertions": 27,
                    "deletions": 0
                },
                {
                    "file": "scripts/update_schemas.py",
                    "type": "MODIFIED",
                    "insertions": 7,
                    "deletions": -6
                }
            ],
            "sizeInsertions": 7,
            "sizeDeletions": 6
        },
        {
            "number": 2,
            "revision": "d699cf969aea5a059b95151f58e054c928f076cc",
            "parents": [
                "dc414b50c19bea912babb00cf8f1e090dbbcc3b7"
            ],
            "ref": "refs/changes/22/45822/2",
            "uploader": {
                "name": "Ed Tanous",
                "email": "ed@tanous.net",
                "username": "edtanous"
            },
            "createdOn": 1629148423,
            "author": {
                "name": "Szymon Dompke",
                "email": "szymon.dompke@intel.com",
                "username": "sdompke"
            },
            "kind": "TRIVIAL_REBASE",
            "files": [
                {
                    "file": "/COMMIT_MSG",
                    "type": "ADDED",
                    "insertions": 27,
                    "deletions": 0
                },
                {
                    "file": "scripts/update_schemas.py",
                    "type": "MODIFIED",
                    "insertions": 7,
                    "deletions": -6
                }
            ],
            "sizeInsertions": 7,
            "sizeDeletions": 6
        }
    ]
}